services:
  client1:  
    build: .
    container_name: client1
    ports:
      - "12345:12345"
    networks:
      - tp2network
    command: ["python3", "client.py"]
  
  client2:
    build: .
    container_name: client2
    ports:
      - "12346:12346"
    networks:
      - tp2network
    command: ["python3", "client.py"]
  
  client3:
    build: .
    container_name: client3
    ports:
      - "12347:12347"
    networks:
      - tp2network
    command: ["python3", "client.py"]

  client4:
    build: .
    container_name: client4
    ports:
      - "12348:12348"
    networks:
      - tp2network
    command: ["python3", "client.py"]
  
  client5:
    build: .
    container_name: client5
    ports:
      - "12349:12349"
    networks:
      - tp2network
    command: ["python3", "client.py"]
networks:
  tp2network:
    external: true