services:
  clusternode1:
    build: .
    container_name: clusternode1
    ports:
      - "12345:12345"
    networks:
      - tp2network
    command: ["python3", "clusternode.py"]
  
  clusternode2:
    build: .
    container_name: clusternode2
    ports:
      - "12346:12346"
    networks:
      - tp2network
    command: ["python3", "clusternode.py"]

  clusternode3:
    build: .
    container_name: clusternode3
    ports:
      - "12347:12347"
    networks:
      - tp2network
    command: ["python3", "clusternode.py"]
  
  clusternode4:
    build: .
    container_name: clusternode4
    ports:
      - "12348:12348"
    networks:
      - tp2network
    command: ["python3", "clusternode.py"]

  clusternode5:
    build: .
    container_name: clusternode5
    ports:
      - "12349:12349"
    networks:
      - tp2network
    command: ["python3", "clusternode.py"]
networks:
  tp2network:
    external: true